sudo: false
language: php
php:
  - 5.6
  - 7.0
  - 7.1
services:
  - memcached
before_script:
  - echo "extension = memcached.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - composer install
script: phpunit --verbose --bootstrap www/config-sample.inc.php tests
