sudo: false
language: php
services:
  - memcached
before_script:
  - echo "extension = memcached.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - composer install
script: phpunit --verbose --bootstrap www/config-sample.inc.php tests
